const axios=require('axios');
const {Client,GatewayIntentBits,EmbedBuilder}=require('discord.js');
const {env}=require('../../config/env');
const {parseJD}=require('../../services/jdParser');
const {parseResume}=require('../../services/resumeParser');
const {scoreResume}=require('../../services/atsEngine');
const {enhance}=require('../../services/aiAnalyzer');
const {formatReport}=require('../../utils/scoreFormatter');
const {saveSession,getSession,clearSession}=require('../../services/sessionManager');
async function attachmentBuffer(url){return Buffer.from((await axios.get(url,{responseType:'arraybuffer',timeout:30000})).data)}
function reportEmbed(report,score){return new EmbedBuilder().setTitle(`ResumeIQ ATS Report — ${score}/100`).setDescription(report.slice(0,4000)).setColor(score>=75?0x2ecc71:score>=50?0xf1c40f:0xe74c3c)}
function createDiscordClient(){if(!env.enableDiscord)return null;if(!env.discord.token)throw new Error('DISCORD_TOKEN is required when ENABLE_DISCORD=true');const client=new Client({intents:[GatewayIntentBits.Guilds]});client.once('ready',()=>console.log(`Discord ready as ${client.user.tag}`));client.on('interactionCreate',async interaction=>{if(!interaction.isChatInputCommand())return;const key=interaction.user.id;try{if(interaction.commandName==='setjd'){const text=interaction.options.getString('description');await saveSession(key,{state:'jd_saved',jobDescription:text,jd:parseJD(text)});return interaction.reply('✅ Job description saved. Now use `/analyze` and attach a PDF, DOCX, or TXT resume.')}if(interaction.commandName==='analyze'){const attachment=interaction.options.getAttachment('resume');if(!attachment)return interaction.reply({content:'Attach a PDF, DOCX, or TXT file using the `resume` option.',ephemeral:true});const session=await getSession(key);if(!session.jd)return interaction.reply({content:'Set a job description first with `/setjd description:...`.',ephemeral:true});await interaction.deferReply();const data=await attachmentBuffer(attachment.url);const resume=await parseResume(data,attachment.name);const result=scoreResume(resume,session.jd);const ai=await enhance(resume,session.jd,result);const report=formatReport({filename:attachment.name,jd:session.jd,result,ai});return interaction.editReply({embeds:[reportEmbed(report,ai.adjustedScore||result.score)]})}if(interaction.commandName==='compare')return interaction.reply({content:'Bulk comparison is not enabled in the Discord starter flow yet. Analyze resumes individually with `/analyze`.',ephemeral:true});}catch(error){const msg=`⚠️ Analysis failed: ${error.message}`;if(interaction.deferred||interaction.replied)return interaction.editReply(msg);return interaction.reply({content:msg,ephemeral:true})}});client.login(env.discord.token);return client}
module.exports={createDiscordClient};
